//Author: God Bennett

import java.util.ArrayList;
import java.util.Scanner;

public class RunNeuralNetwork
{
    ///features 
    private static Scanner userScanner = new Scanner ( System.in );
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    
    public static void main ( String [ ] aiStuff )
    {
		doTraining ( );
        doMainMenu ( );
    }
    
    //surpervise neural network
    public static void doTraining ( )
    {
        ArrayList <String> trainingData = getTrainingData ( );
        
        for ( int tDI = 0; tDI < trainingData.size ( ); tDI ++ )
        {
            //forward prop
            String leftHandSide = trainingData.get ( tDI ).split ( ":" ) [0];
            int component0 = Integer.parseInt( leftHandSide.split ( "," ) [ 0 ] );
            int component1 = Integer.parseInt( leftHandSide.split ( "," ) [ 1 ] );
            int inputSignals [ ] = new int [ ] { component0, component1 };
            
            neuralNetwork.doForwardPropagation ( inputSignals );
            
            //back propagation
            int rightHandSide = Integer.parseInt( trainingData.get ( tDI ).split ( ":" ) [1] );
            
            neuralNetwork.doBackwardPropagation ( rightHandSide );
        }
    }
    
    //testing
    public static void doMainMenu ( )
    {
        System.out.println ( "NCB Basic Neural Network Live coding session 12-18-2020" );
        System.out.println ( "1. Get neural network answer for input [0,0]" );
        System.out.println ( "2. Get neural network answer for input [0,1]" );
        System.out.println ( "3. Get neural network answer for input [1,0]" );
        System.out.println ( "4. Get neural network answer for input [1,1]" );
        System.out.println ( "5. Get me out of here please!" );
        System.out.println ( "Please select an option" );
        
        int userInput = userScanner.nextInt ( );
        
        switch ( userInput ) 
        {
            case  1:
            {
                int inputs [ ] = new int [ ] { 0, 0 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network guess at input [0,0] = " + neuralNetwork.getOutcome ( ) );
                
                 returnToMainMenu ( );
            }
            break;
            case  2:
            {
                int inputs [ ] = new int [ ] { 0, 1 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network guess at input [0,1] = " + neuralNetwork.getOutcome ( ) );
                
                 returnToMainMenu ( );
            }
            break;
            case  3:
            {
                int inputs [ ] = new int [ ] { 1, 0 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network guess at input [1,0] = " + neuralNetwork.getOutcome ( ) );
                
                 returnToMainMenu ( );
            }
            break;
            case  4:
            {
                int inputs [ ] = new int [ ] { 1, 1 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network guess at input [1,1] = " + neuralNetwork.getOutcome ( ) );
                
                 returnToMainMenu ( );
            }
            break;
            case  5:
            {
                System.exit ( 0 );
            }
            break;
        }
    }
    
    public static void returnToMainMenu ( )
    {
        System.out.println ( "/f" );
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        doMainMenu ( );
    }
    
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );

        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
  
        
        return returnValue;
    }
}
